module.exports = [
  {
    name: "OpenAI completions",
    model: "gpt-5.1",
    api_key: process.env.OPENAI_API_KEY,
    backend: "OpenAI",
    embed_model: "text-embedding-3-small",
    image_model: "gpt-image-1",
    temperature: 0.7,
    responses_api: false,
    ai_sdk_provider: "OpenAI",
  },
  {
    name: "OpenAI responses",
    model: "gpt-5.1",
    api_key: process.env.OPENAI_API_KEY,
    backend: "OpenAI",
    embed_model: "text-embedding-3-small",
    image_model: "gpt-image-1",
    temperature: 0.7,
    responses_api: true,
    ai_sdk_provider: "OpenAI",
  },
  {
    name: "AI SDK OpenAI",
    model: "gpt-5.1",
    api_key: process.env.OPENAI_API_KEY,
    backend: "AI SDK",
    embed_model: "text-embedding-3-small",
    image_model: "gpt-image-1",
    temperature: 0.7,
    ai_sdk_provider: "OpenAI",
  },
];
